package markdown

import (
	"strings"
	"testing"
)

func TestDocumentRenderSkipsEmptyHeadingForCommentOnlySection(t *testing.T) {
	doc := Document{
		Title:    "Demo",
		Preamble: []string{"> intro"},
		Sections: []Section{
			{Comment: "generated by makemd"},
			NewSection("Usage", "Run it"),
			{Title: "Hidden", Body: "skip me", Hidden: true},
		},
	}

	got := doc.Render()

	if strings.Contains(got, "## \n") {
		t.Fatalf("rendered an empty section heading:\n%s", got)
	}
	if !strings.Contains(got, "<!-- generated by makemd -->") {
		t.Fatalf("expected generated comment in output:\n%s", got)
	}
	if strings.Contains(got, "Hidden") {
		t.Fatalf("expected hidden section to be skipped:\n%s", got)
	}
}

func TestEditorWorkflow(t *testing.T) {
	content := "# Demo\n\n> Intro\n\n## Install\n\nOld install\n\n## Usage\n\nOld usage\n"

	editor := NewEditor(content)
	editor.SetTitle("Updated Demo")
	editor.SetSection("Usage", "Run it")
	editor.RemoveSection("Install")
	editor.AppendSection("Examples", "Example body")
	editor.UpsertTOC("Table of Contents")
	editor.InsertBadges([]string{"![CI](https://example.com/ci.svg)"})

	got := editor.Render()

	for _, want := range []string{
		"# Updated Demo",
		"![CI](https://example.com/ci.svg)",
		"> Intro",
		"## Table of Contents",
		"- [Usage](#usage)",
		"- [Examples](#examples)",
		"## Usage\n\nRun it",
		"## Examples\n\nExample body",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected output to contain %q:\n%s", want, got)
		}
	}

	if strings.Contains(got, "## Install") {
		t.Fatalf("expected Install section to be removed:\n%s", got)
	}
}

func TestHelpersRenderExpectedMarkdown(t *testing.T) {
	if got, want := Badge("CI", "https://example.com/badge.svg", "https://example.com"), "[![CI](https://example.com/badge.svg)](https://example.com)"; got != want {
		t.Fatalf("unexpected badge output:\nwant: %s\ngot:  %s", want, got)
	}

	if got, want := BlockQuote("line one\nline two"), "> line one\n> line two"; got != want {
		t.Fatalf("unexpected blockquote output:\nwant: %s\ngot:  %s", want, got)
	}

	if got, want := CodeBlock("sh", "echo hi"), "```sh\necho hi\n```\n"; got != want {
		t.Fatalf("unexpected code block output:\nwant: %q\ngot:  %q", want, got)
	}

	if got, want := Bullets("one", "", "two"), "- one\n- two"; got != want {
		t.Fatalf("unexpected bullets output:\nwant: %s\ngot:  %s", want, got)
	}

	if got, want := Numbered("one", "two"), "1. one\n2. two"; got != want {
		t.Fatalf("unexpected numbered output:\nwant: %s\ngot:  %s", want, got)
	}

	if got, want := Table([]string{"Name", "Value"}, [][]string{{"alpha", "one|two"}}), "| Name | Value |\n| --- | --- |\n| alpha | one\\|two |"; got != want {
		t.Fatalf("unexpected table output:\nwant:\n%s\ngot:\n%s", want, got)
	}

	if got, want := Anchor("Hello, World."), "hello-world"; got != want {
		t.Fatalf("unexpected anchor output: want %q got %q", want, got)
	}

	toc := TOCFromSections([]Section{
		{Level: 2, Title: "Overview"},
		{Level: 3, Title: "Details"},
		{Level: 2, Title: "", Body: "ignored"},
	})
	if got, want := toc, "- [Overview](#overview)\n\t- [Details](#details)"; got != want {
		t.Fatalf("unexpected toc output:\nwant:\n%s\ngot:\n%s", want, got)
	}

	sections := []Section{
		{Title: "beta"},
		{Title: "Alpha"},
	}
	SortSectionsByTitle(sections)
	if sections[0].Title != "Alpha" || sections[1].Title != "beta" {
		t.Fatalf("unexpected sort order: %#v", sections)
	}
}
